---
# tasks file for rsysloging-client

- name: "Assert all required variables are set"
  fail: msg="Variable '{{ item }}' is not defined!"
  when: item not in vars
  with_items: "{{ clc_required_vars }}"

- name: Include os variables
  include_vars: "{{ansible_os_family}}.yml"

- name: Update apt packages
  become: true
  apt:
    # upgrade: yes
    update_cache: yes

- include: rsyslog.yml
