---

- name: "Check the existence of the rsyslog."
  apt:
    name: rsyslog
    state: present

- name: "getent passwd"
  getent:
    database: passwd

- name: Get list of valid shells
  shell: cat /etc/shells | grep -v '# /etc/shells'
  register: shells

- name: Set variables (slm_login_shells, empty slm_user_history_file_pairs)
  set_fact: 
    slm_login_shells: "{{ shells.stdout_lines }}"
    slm_user_history_file_pairs: []

- name: "Modify slm_user_history_file_pairs to contains key/value pairs ( user : path to history file )"
  set_fact:
    slm_user_history_file_pairs:  "{{ slm_user_history_file_pairs + [{ 'key': item.key, 'value':  item.value[4] + '/.msf4/history' }] }}"
  when: item.value[5] in slm_login_shells
  loop: "{{ getent_passwd | dict2items }}"

- name: Ensures .msf4 directories exist
  file: 
    path: "{{ item.value | dirname }}"
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
    mode: 0755
    state: directory
  loop: "{{ slm_user_history_file_pairs }}"

- name: Create history files
  file:
    path: "{{ item.value }}"
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
    mode: 0644
    state: touch
    modification_time: preserve
    access_time: preserve
  loop: "{{ slm_user_history_file_pairs }}"

- name: "150-msf.conf"
  template:
    src: 150-msf.conf.j2
    dest: /etc/rsyslog.d/150-msf.conf
  become: yes

- name: "Change to root ownership of syslog. This is to make sure auditd starts properly."
  file:
    path: /var/log/syslog
    owner: root
    group: root
  become: yes

- name: "Restart rsyslog service"
  service:
    name: rsyslog
    state: restarted
    enabled: yes

